## /config/packages/octopowerup.yaml
## imap email processing
sensor:
template:
  - trigger:
      - platform: event
        event_type: "imap_content"
        id: "custom_event"
        event_data:
          custom: True
    sensor:
      - name: OctopusPowerUp
        state: "{{ trigger.event.data['subject'] }}"
        attributes:
          Message: "{{ trigger.event.data['text'] }}"
          Server: "{{ trigger.event.data['server'] }}"
          Username: "{{ trigger.event.data['username'] }}"
          Search: "{{ trigger.event.data['search'] }}"
          Folder: "{{ trigger.event.data['folder'] }}"
          Sender: "{{ trigger.event.data['sender'] }}"
          Date: "{{ trigger.event.data['date'] }}"
          Subject: "{{ trigger.event.data['subject'] }}"
          Initial: "{{ trigger.event.data['initial'] }}"
          To: "{{ trigger.event.data['headers'].get('Delivered-To', ['n/a'])[0] }}"
          Return-Path: "{{ trigger.event.data['headers'].get('Return-Path',['n/a'])[0] }}"
          Received-first: "{{ trigger.event.data['headers'].get('Received',['n/a'])[0] }}"
          Received-last: "{{ trigger.event.data['headers'].get('Received',['n/a'])[-1] }}"

      - name: octopoweruplink
        state: >
            {{ state_attr( 'sensor.OctopusPowerUp','Message')
             | regex_replace(find='\r\n', replace="") 
             | regex_findall_index('https:\/\/\S+', index=0) }}
             
      - name: OctoPowerUpDate
        state: >
            {% set t = state_attr( 'sensor.OctopusPowerUp','Subject') 
             | regex_findall_index('(\d+\/\d+\/\d+)')
             | regex_replace(find="\/", replace="-") %}
             {{20}}{{t[6]}}{{t[7]}}{{t[5]}}{{t[8]}}{{t[0]}}{{t[1]}}{{t[2]}}{{t[3]}}{{t[4]}}
 
      - name: OctoPowerUpStart
        state: >
          {% set t = state_attr('sensor.OctopusPowerUp', 'Subject') 
            | regex_findall_index('(\d+):(\d+) ([A|P]M)', index=0) %}
           {% set y = t[0] |int %}
           {% if 'PM' in t[2] %} {% set x = y+12 %}
           {% else %} {% set x = y+0 %}
           {% endif %}
           {{states('sensor.octopowerupdate', rounded=True, with_unit=True)}}{{' '}}{{x}}{{':'}}{{t[1]}}{{':00'}}

      - name: OctoPowerUpEnd
        state: >
          {% set t = state_attr('sensor.OctopusPowerUp', 'Subject') 
            | regex_findall_index('(\d+):(\d+) ([A|P]M)', index=1) %}
           {% set y = t[0] |int %}
           {% if 'PM' in t[2] %} {% set x = y+12 %}
           {% else %} {% set x = y+0 %}
           {% endif %}
           {{states('sensor.octopowerupdate', rounded=True, with_unit=True)}}{{' '}}{{x}}{{':'}}{{t[1]}}{{':00'}}
 
      - name: octopowerupstartts
        state: > 
            {{ as_timestamp(strptime(states('sensor.octopowerupstart'), "%Y-%d-%m %H:%M:%S" ))| int(0) }}
        icon: "mdi:calendar-clock"

      - name: octopowerupendts
        state: > 
            {{ as_timestamp(strptime(states('sensor.OctoPowerUpEnd'), "%Y-%d-%m %H:%M:%S" )) | int(0) }}
        icon: "mdi:calendar-clock"

 
